# coding: utf-8

"""
    TinyMLaaS

    TinyMLaaS Ecosystem for Machine Learning in IoT  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.models_.get import GetAllModelsModelsGet
from openapi_client.paths.models_datasets_.post import TrainModelDatasetIdInTrainingDataModelsDatasetsPost
from openapi_client.paths.models_datasets_dataset_id.post import TrainModelModelsDatasetsDatasetIdPost


class ModelsApi(
    GetAllModelsModelsGet,
    TrainModelDatasetIdInTrainingDataModelsDatasetsPost,
    TrainModelModelsDatasetsDatasetIdPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
