# coding: utf-8

"""
    TinyMLaaS

    TinyMLaaS Ecosystem for Machine Learning in IoT  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.model_trained import ModelTrained
from openapi_client import configuration


class TestModelTrained(unittest.TestCase):
    """ModelTrained unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
