# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import openapi_client
from openapi_client.paths.compiled_models_compiled_model_id_bridges_bridge_id_devices_device_id import post  # noqa: E501
from openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestCompiledModelsCompiledModelIdBridgesBridgeIdDevicesDeviceId(ApiTestMixin, unittest.TestCase):
    """
    CompiledModelsCompiledModelIdBridgesBridgeIdDevicesDeviceId unit test stubs
        Install Model To Device On Brdige  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
