# coding: utf-8

"""
    TinyMLaaS

    TinyMLaaS Ecosystem for Machine Learning in IoT  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.compiled_models_models_model_id.post import CompileModelCompiledModelsModelsModelIdPost
from openapi_client.paths.compiled_models_compiled_model_id.get import GetCompiledModelCompiledModelsCompiledModelIdGet
from openapi_client.paths.compiled_models_.get import GetCompiledModelsCompiledModelsGet
from openapi_client.paths.compiled_models_compiled_model_id_bridges_bridge_id_devices_device_id.post import InstallModelToDeviceOnBrdigeCompiledModelsCompiledModelIdBridgesBridgeIdDevicesDeviceIdPost


class CompiledModelsApi(
    CompileModelCompiledModelsModelsModelIdPost,
    GetCompiledModelCompiledModelsCompiledModelIdGet,
    GetCompiledModelsCompiledModelsGet,
    InstallModelToDeviceOnBrdigeCompiledModelsCompiledModelIdBridgesBridgeIdDevicesDeviceIdPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
